### ISSUE TITLE
Orion provider not included

### ISSUE THREAD

**Issue by ikstewa** [JakedUp/Syncler-Packages#10]
It appears the orion provider is no longer included in the hybrid results.

Loading the provider directly via `https://wako.orionoid.com/<MY_API_KEY>` I see the config with a `baseUrl` of `https://api.orionoid.com` and a `query` with a token parameter containing a unique token.

When generating via `https://syncler-providers.herokuapp.com/syncler/express-hybrid.json?orion-api-key=<MY_API_KEY>` there are no providers referencing the orionoid api. Additionally I do not see any reference to the unique token found when loading from the Orion wako URL.

**Comment by brentonv** [comment]
It seems to be working. This is comparing api **_'key.txt'_** with **_'nokey.txt'_** and you can see it adds the Orion provider

![compare](https://github.com/JakedUp/Syncler-Packages/assets/2313757/fc780a2c-2f8b-471b-9220-c5ba02de37bb)

The **_'keyresult.txt'_** shows a successful query using the generated link: https://api.orionoid.com/?token=56XGIURMJRYDSAGLQFTCADRWWUURT4F4IJOWGULMUQG7DYGPK7JBATSDNKGIKPLBZO33SMVATDLINSEI2BZU5VE66C32M2CICHV2OTF4NHR2622AG4VKZMRV6SOCVD3J&mode=stream&action=retrieve&output=wako&type=movie&streamtype=torrent&protocoltorrent=magnet&filename=true&fileunknown=false&limitcount=200&sortvalue=streamseeds&sortorder=descending&videoquality=sd_hd8k&audiochannels=2_&access=false&lookup=false&idimdb={imdbId}&query=mad+max%22

![response](https://github.com/JakedUp/Syncler-Packages/assets/2313757/e8f68ca0-f1a5-4e04-98db-9206ed3e8221)

**Comment by JakedUp** [comment]
Not sure what could be causing this, but Orion has been confirmed working by numerous people over the past couple of weeks. I would double-check the API key you are providing. Worst case, you can PM me your API key and I can investigate.

**Comment by ikstewa** [comment]
It is now working with my API key. Sorry for the false alarm.
