### ISSUE TITLE
Continue source search after source selection [not stopping]

### ISSUE THREAD

**Issue by Qutaiba-Khader** [JakedUp/Syncler-Packages#7]
The option
 ((Continue source search after source selection))

Is not working, it's keep searching anyway doesn't matter (on/off)

![IMG_20220222_181427](https://user-images.githubusercontent.com/6103683/155173748-00907452-ad86-4626-9322-726772ef50ff.jpg)

**Comment by JakedUp** [comment]
This is an app bug, not anything related to the package provider.

**Comment by JakedUp** [comment]
This is an app bug, not anything related to the package provider.
