### ISSUE TITLE
Links are now invalid

### ISSUE THREAD

**Issue by devalberg** [JakedUp/Syncler-Packages#9]
Heroku has shut down their free tier so the links are out 😢

**Comment by TheCWarner** [comment]
What does this mean we should change from Bouncy Kosmos packages to another Kosmos package ?

**Comment by TheCWarner** [comment]
Or swap from jacked Up to another rather

**Comment by devalberg** [comment]
> Or swap from jacked Up to another rather

I guess that's the solution for now 🤷
